<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<img style="position:absolute;top:0.29in;left:0.29in;width:8.44in;height:12.09in" src="https://i.ibb.co/sWMqqt9/vi-1.png" />
<img style="position:absolute;top:0.37in;left:0.37in;width:0.84in;height:0.84in" src="https://i.ibb.co/02QNgcx/ri-1.png" />

<div style="position:absolute;top:0.44in;left:1.25in;width:1.20in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Department of Agriculture</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.69in;left:1.25in;width:1.00in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Diliman, Quezon City</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.94in;left:1.25in;width:1.98in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Trunk Line(02)8928-8756 to 65 Local 2472</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Email Add:bafe@da.gov.ph</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.30in;left:0.92in;width:1.44in;line-height:0.12in;"><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">SRED-ARS-PTOWO-21-02-__</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.03in;left:3.69in;width:1.67in;line-height:0.27in;"><span style="font-style:italic;font-weight:bold;font-size:15pt;font-family:Helvetica;color:#000000">WORK ORDER</span><span style="font-style:italic;font-weight:bold;font-size:15pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.89in;left:0.92in;width:7.28in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">This is to authorize the bearer/s whose name/s and signature/s appears below, to conduct on-site inspection and evaluation for the registration and issuance</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">of permit </span></SPAN><br/></div>
<div style="position:absolute;top:4.01in;left:0.92in;width:7.28in;line-height:0.12in;"><DIV style="position:relative; left:0.50in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">to operate </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.01in;left:0.92in;width:7.28in;line-height:0.12in;"><DIV style="position:relative; left:1.07in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">for agricultural and </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.01in;left:0.92in;width:7.28in;line-height:0.12in;"><DIV style="position:relative; left:2.06in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">fisheries machinery manufacturers, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.01in;left:0.92in;width:7.28in;line-height:0.12in;"><DIV style="position:relative; left:3.80in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">fabricators, assemblers, distributors, dealers, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.01in;left:0.92in;width:7.28in;line-height:0.12in;"><DIV style="position:relative; left:6.03in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">importers, and exporters</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.73in;left:0.92in;width:1.16in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">CONTROL NO:</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> 21-P007</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.32in;left:0.92in;width:0.89in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">DATE: </span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">2023-05-23</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.91in;left:0.92in;width:1.79in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">MFADDIE: </span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">Suki Trading Corporation</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.13in;left:0.92in;width:2.29in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Address: </span><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Fuentes, Agus Ibabao,Lapu-Lapu, Cebu</span><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.73in;left:0.92in;width:0.73in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">INSPECTORS:</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.45in;left:0.92in;width:0.65in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Approved By:</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.05in;left:0.92in;width:1.35in;line-height:0.12in;"><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">ENGR. ARIODEAR C. RICO</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">Director IV</span><span style="font-style:italic;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.55in;left:0.92in;width:0.51in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Conforme:</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.15in;left:0.92in;width:2.95in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">___________________________________________________</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Name and Signature of the Applicant/</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.64in;left:0.92in;width:2.77in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Date: ___________________________________________</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
</body>
</html>
